### PR TITLE
Added listening any event functionality

### PR DESCRIPTION
**Pull request by busslina**

### CODE REVIEW

**Comment by jumperchen** [comment]
Thanks for the contribution.

**Comment by jumperchen** [comment]
memo: same feature as described on https://socket.io/docs/v4/client-api/#socketonanycallback

**Comment by busslina** [comment]
I'm currently using this feature in 'local mode'. I think you forgot to update the 'client' repo to use the latest 'common' repo.
Thank you

**Comment by jumperchen** [comment]
you can run `pub upgrade` to use the latest version instead.

**Pull request merged**
