### PR TITLE
fix: :bug: regression bug toJson

### PR DESCRIPTION
**Pull request by sergiomeneses**
Fix #12 regression bug on toJson.

### CODE REVIEW

**Comment by jumperchen** [comment]
Thanks for your contribution.

Did you run this test case? - https://github.com/rikulo/socket_io_common/blob/master/test/isBinary.test.dart

**Comment by sergiomeneses** [comment]
I did, all test returns false, note that even without this changes some test returns false, also the test was created with the regression commit. I think the changes between `3.0.0-beta.0` to  `3.0.0` introduce a buggy implementation.

Also i dont really sure that the `toJSON` method is a typo and should be `toJson`.

I found the error `NoSuchMethod` when the `isBinary` hit  the line `var toJsonMethod = obj.toJSON;`  using a custom class that use `json_annotation` as data on `emit` method on socket.

**Comment by jumperchen** [comment]
Yes, `toJson` should be correct one - https://github.com/dart-lang/sdk/blob/9e1ac0881791f189f98b211076b9772bfade56ed/pkg/json/lib/json.dart#L12

**Comment by jumperchen** [comment]
@sergiomeneses I refine the logic and change the testing file to see if this change works for your case.
If so, I will release a 3.0.1 version for you.

**Comment by sergiomeneses** [comment]
@jumperchen stills the same error, if i remove this lines from `hasBinary function`, works:

```dart
// Check if the object has a toJSON method, regardless of its type (Map, custom object, etc.)
  var toJsonMethod = _getToJsonMethod(obj);
  if (toJsonMethod != null && toJSON == false) {
    return hasBinary(toJsonMethod(), true);
  }
  ```

may this need some kind of reflection.

**Comment by jumperchen** [comment]
do you have a test case for me to test?

**Comment by sergiomeneses** [comment]
The error happend even using plain data:

```dart

final socket = IO.io(
      baseUrl,
      IO.OptionBuilder()
          .setTransports(['websocket'])
          .disableAutoConnect()
          .enableForceNew()
          .setReconnectionAttempts(5)
          .setReconnectionDelay(5000)
          .build(),
    );

socket.emit('login', 'plain'); //<--- 'NoSuchMethod'

final request = LoginRequestSocket(uuid: touristUuid).toJson();
 socket.emit('login', request); //<--- 'NoSuchMethod'
 ```
 
```dart 
import 'package:json_annotation/json_annotation.dart';

part 'login_socket.g.dart';
 @JsonSerializable()
class LoginRequestSocket {
  const LoginRequestSocket({required this.uuid});
  final String uuid;

  factory LoginRequestSocket.fromJson(Map<String, dynamic> json) =>
      _$LoginRequestSocketFromJson(json);

  Map<String, dynamic> toJson() => _$LoginRequestSocketToJson(this);
}
 ```

**Comment by jumperchen** [comment]
strange, I run your example in my env. with Dart 3.4.1 (stable), and it doesn't throw the NoSuchMethod error.

**Comment by sergiomeneses** [comment]
I have `Dart SDK version: 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "linux_x64"`

```
• Flutter version 3.24.3 on channel stable at /home/*******/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 2663184aa7 (6 weeks ago), 2024-09-11 16:27:48 -0500
• Engine revision 36335019a8
• Dart version 3.5.3
• DevTools version 2.37.3
```

**Comment by jumperchen** [comment]
This is my env. info:
```
Flutter is already up to date on channel stable
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (23 hours ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3
```
The Flutter app is running on the Android simulator, and I have set a breakpoint in the `_getToJsonMethod`. It did not throw any errors; instead, it returned a null value as below.
image

To me, the code logic is correct. Any errors should be caught in the try-catch statement, so I don't understand why it behaves incorrectly in your environment.

**Comment by sergiomeneses** [comment]
Very strange this, also i am testing in a real device, let me create a reproducible error next week.

**Comment by sergiomeneses** [comment]
I really dont know why is this happening, so i make a new application and all works as expected, (i use the `3.0.1`), closed as ureproducible

**Pull request closed without merging**
